//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace f0t0vi3w3r.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.jpg;*.jpeg/*.png/*.tif/*.bmp/*.gif")]
        public string Extensions {
            get {
                return ((string)(this["Extensions"]));
            }
            set {
                this["Extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTinyImage {
            get {
                return ((bool)(this["ShowTinyImage"]));
            }
            set {
                this["ShowTinyImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatSlideShow {
            get {
                return ((bool)(this["RepeatSlideShow"]));
            }
            set {
                this["RepeatSlideShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartMaximized {
            get {
                return ((bool)(this["StartMaximized"]));
            }
            set {
                this["StartMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoNavigation {
            get {
                return ((bool)(this["AutoNavigation"]));
            }
            set {
                this["AutoNavigation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloneBoxNavigation {
            get {
                return ((bool)(this["CloneBoxNavigation"]));
            }
            set {
                this["CloneBoxNavigation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint AutoRepeatDelay {
            get {
                return ((uint)(this["AutoRepeatDelay"]));
            }
            set {
                this["AutoRepeatDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public uint TabCharacters {
            get {
                return ((uint)(this["TabCharacters"]));
            }
            set {
                this["TabCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint HashSize {
            get {
                return ((uint)(this["HashSize"]));
            }
            set {
                this["HashSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowBorder {
            get {
                return ((bool)(this["ShowBorder"]));
            }
            set {
                this["ShowBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuBar {
            get {
                return ((bool)(this["ShowMenuBar"]));
            }
            set {
                this["ShowMenuBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hello n00b,\\nHow the **** can\'t you use a picture viewer application? Click on fi" +
            "le and do junk.\\nIf you can\'t use this, noone can help you :).\\nNow close the ap" +
            "plication slowly and back away from your computer!!!\\n\\nThanks!")]
        public string HelloN00bString {
            get {
                return ((string)(this["HelloN00bString"]));
            }
            set {
                this["HelloN00bString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vertical")]
        public global::System.Windows.Forms.Orientation DefaultOrientation {
            get {
                return ((global::System.Windows.Forms.Orientation)(this["DefaultOrientation"]));
            }
            set {
                this["DefaultOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint SlideShowDelay {
            get {
                return ((uint)(this["SlideShowDelay"]));
            }
            set {
                this["SlideShowDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomizeSlideShow {
            get {
                return ((bool)(this["RandomizeSlideShow"]));
            }
            set {
                this["RandomizeSlideShow"] = value;
            }
        }
    }
}
